district: "Gravois Trails"
unit_type: "Pack"
unit_number: "3721"
coffee_link: "https://gatewaytraders.org/collections/gslac-coffee"
popcorn_base_link: "https://trails-end.com/store/scout/"
scout_type: "Cub Scout"
google_analytics: "G-8C7LBN3MZT"